//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AverinApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ShipmentOfProduct = new HashSet<ShipmentOfProduct>();
            this.SupplyOfProduct = new HashSet<SupplyOfProduct>();
            this.WarehouseOfProduct = new HashSet<WarehouseOfProduct>();
        }
    
        public string Number { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string MeasureUnit { get; set; }
        public decimal Weight { get; set; }
        public string CertificateNumber { get; set; }
        public decimal Price { get; set; }
    
        public virtual Certificate Certificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentOfProduct> ShipmentOfProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyOfProduct> SupplyOfProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseOfProduct> WarehouseOfProduct { get; set; }
    }
}
