//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AverinApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public string Number { get; set; }
        public int WarehouseId { get; set; }
        public string SupplyNumber { get; set; }
        public string ShipmentContractNumber { get; set; }
    
        public virtual ShipmentContract ShipmentContract { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
