//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AverinApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentOfProduct
    {
        public int Id { get; set; }
        public int ShipmentId { get; set; }
        public string ProductNumber { get; set; }
        public decimal Count { get; set; }
    
        public virtual Shipment Shipment { get; set; }
    }
}
