//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AverinApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supply()
        {
            this.SupplyOfProduct = new HashSet<SupplyOfProduct>();
        }
    
        public int Id { get; set; }
        public int ProviderId { get; set; }
        public string SupplyContractNumber { get; set; }
        public int StatusId { get; set; }
        public int WarehouseId { get; set; }
        public Nullable<int> OperatorId { get; set; }
    
        public virtual Operator Operator { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Status Status { get; set; }
        public virtual SupplyContract SupplyContract { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyOfProduct> SupplyOfProduct { get; set; }
    }
}
